version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file samTemp.yml --s3-bucket pipeline-samaritan --output-template-file UnpdatedsamTemp.yml
artifacts:
  files:
    - UnpdatedsamTemp.yml
